name: Validate

on:
  push: 
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4.1.7
        
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: plugin
